
-- list all the assignement from the appraiser
CREATE VIEW APPRAISER_ASSIGNEMENT AS
SELECT e.USER_ID , e.name, e.SURNAME, a.EVAL_DATE, a.APPRAISAL_ID as 'YOURSELF_ID', a.STATUS ,
    LM.APPRAISAL_ID AS 'LM_ID', LM.STATUS AS 'LM_STATUS', LM.EVALUATED_PERSON_ID AS 'LM_USER_ID', LM.NAME AS 'LM_NAME', LM.SURNAME as 'LM_SURNAME',
    TL.APPRAISAL_ID AS 'TL_ID', TL.STATUS AS 'TL_STATUS', TL.EVALUATED_PERSON_ID AS 'TL_USER_ID', TL.NAME AS 'TL_NAME', TL.SURNAME as 'TL_SURNAME',
    MT.APPRAISAL_ID AS 'MT_ID', MT.STATUS AS 'MT_STATUS', MT.EVALUATED_PERSON_ID AS 'MT_USER_ID', MT.NAME AS 'MT_NAME', MT.SURNAME as 'MT_SURNAME',
    TM.APPRAISAL_ID AS 'TM_ID', TM.STATUS AS 'TM_STATUS', TM.EVALUATED_PERSON_ID AS 'TM_USER_ID', TM.NAME AS 'TM_NAME', TM.SURNAME as 'TM_SURNAME',
    GM.APPRAISAL_ID AS 'GM_ID', GM.STATUS AS 'GM_STATUS', GM.EVALUATED_PERSON_ID AS 'GM_USER_ID', GM.NAME AS 'GM_NAME', GM.SURNAME as 'GM_SURNAME'
FROM  EMPLOYEE e 
    INNER JOIN APPRAISAL a ON e.USER_ID = a.APPRAISER_ID
    OUTER APPLY  (SELECT a2.APPRAISAL_ID , a2.EVALUATED_PERSON_ID , e2.NAME , e2.SURNAME , a2.STATUS FROM APPRAISAL a2 INNER JOIN EMPLOYEE e2 ON e2.USER_ID = a2.EVALUATED_PERSON_ID WHERE a2.APPRAISER_ID = e.USER_ID AND a2.EVAL_DATE = a.EVAL_DATE AND [TYPE] ='EVALUATED_2_LINE_MANAGER') AS LM
    OUTER APPLY  (SELECT a3.APPRAISAL_ID , a3.EVALUATED_PERSON_ID , e3.NAME , e3.SURNAME , a3.STATUS FROM APPRAISAL a3 INNER JOIN EMPLOYEE e3 ON e3.USER_ID = a3.EVALUATED_PERSON_ID WHERE a3.APPRAISER_ID = e.USER_ID AND a3.EVAL_DATE = a.EVAL_DATE AND [TYPE] ='EVALUATED_2_TEAM_LEAD') AS TL
    OUTER APPLY  (SELECT a4.APPRAISAL_ID , a4.EVALUATED_PERSON_ID , e4.NAME , e4.SURNAME , a4.STATUS FROM APPRAISAL a4 INNER JOIN EMPLOYEE e4 ON e4.USER_ID = a4.EVALUATED_PERSON_ID WHERE a4.APPRAISER_ID = e.USER_ID AND a4.EVAL_DATE = a.EVAL_DATE AND [TYPE] ='EVALUATED_2_MENTOR') AS MT
    OUTER APPLY  (SELECT a5.APPRAISAL_ID , a5.EVALUATED_PERSON_ID , e5.NAME , e5.SURNAME , a5.STATUS FROM APPRAISAL a5 INNER JOIN EMPLOYEE e5 ON e5.USER_ID = a5.EVALUATED_PERSON_ID WHERE a5.APPRAISER_ID = e.USER_ID AND a5.EVAL_DATE = a.EVAL_DATE AND [TYPE] ='TEAMMATE') AS TM
    OUTER APPLY  (SELECT a6.APPRAISAL_ID , a6.EVALUATED_PERSON_ID , e6.NAME , e6.SURNAME , a6.STATUS FROM APPRAISAL a6 INNER JOIN EMPLOYEE e6 ON e6.USER_ID = a6.EVALUATED_PERSON_ID WHERE a6.APPRAISER_ID = e.USER_ID AND a6.EVAL_DATE = a.EVAL_DATE AND [TYPE] ='GROUPMATE') AS GM
WHERE a.[TYPE] = 'YOURSELF' 


-- crear queries para dectectar gente que no esté valorada por teammates or groupmates