
spring:
  datasource:
    url: jdbc:sqlserver://localhost;databasename=evaluationTool360;integratedSecurity=true
    username: sa2
    password: NewPassword
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  resources.add-mappings: true
  
#  #Security
#  #Disable spring seecurity
#  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration