DROP 
  TABLE IF EXISTS EMPLOYEE;
DROP 
  TABLE IF EXISTS ROLE;
DROP 
  TABLE IF EXISTS OFFICE;
DROP 
  TABLE IF EXISTS TEAM;
DROP 
  TABLE IF EXISTS EMPLOYEE_TEAM;
DROP 
  TABLE IF EXISTS EMPLOYEE_GROUP;
DROP 
  TABLE IF EXISTS GROUPS;
DROP 
  TABLE IF EXISTS APPRAISAL;
DROP 
  TABLE IF EXISTS APPRAISAL_ITEM;
DROP 
  TABLE IF EXISTS APPRAISAL_TYPE;
DROP 
  TABLE IF EXISTS SPECIFIC_APPRAISAL_TYPE;
DROP 
  TABLE IF EXISTS GLOBAL_APPRAISAL_TYPE;
DROP 
  TABLE IF EXISTS SPECIFIC_INTERNAL_APPTYPE;
DROP 
  TABLE IF EXISTS GLOBAL_INTERNAL_APPTYPE;
DROP 
  TABLE IF EXISTS APPRAISAL_AVERAGES;
DROP 
  TABLE IF EXISTS CRITERIA_NAME;
  