  
CREATE TABLE ROLE (
  ROLE_ID INT IDENTITY PRIMARY KEY, 
  ROLE_NAME VARCHAR(50)
);
CREATE TABLE OFFICE (
  OFFICE_ID INT IDENTITY PRIMARY KEY, 
  OFFICE_NAME VARCHAR (20)
);
CREATE TABLE TEAM (
  TEAM_ID INT IDENTITY PRIMARY KEY, 
  TEAM_NAME VARCHAR (20)
);
CREATE TABLE EMPLOYEE (
  USER_ID INT IDENTITY PRIMARY KEY, 
  NAME VARCHAR(50), 
  SURNAME VARCHAR(50), 
  EMAIL VARCHAR(50), 
  PASSWORD VARCHAR(100), 
  ROLE_ID INT REFERENCES ROLE, 
  OFFICE_ID INT REFERENCES OFFICE, 
  APPLICATIONROLE VARCHAR(20), 
  MENTOR_ID INT DEFAULT 0, 
  CONSTRAINT MENTOR_FK FOREIGN KEY (MENTOR_ID) REFERENCES EMPLOYEE (USER_ID)
);
CREATE TABLE EMPLOYEE_TEAM (
  USER_ID INT NOT NULL REFERENCES EMPLOYEE, 
  TEAM_ID INT NOT NULL REFERENCES TEAM, 
  FOREIGN KEY (USER_ID) REFERENCES EMPLOYEE (USER_ID), 
  FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID), 
  PRIMARY KEY (USER_ID, TEAM_ID)
);
CREATE TABLE GROUPS (
  GROUP_ID INT IDENTITY PRIMARY KEY, 
  GROUP_NAME VARCHAR (100)
);
CREATE TABLE EMPLOYEE_GROUP (
  USER_ID INT NOT NULL REFERENCES EMPLOYEE, 
  GROUP_ID INT NOT NULL REFERENCES GROUPS, 
  CONSTRAINT EMPL_GROUP_FK FOREIGN KEY (USER_ID) REFERENCES EMPLOYEE (USER_ID), 
  CONSTRAINT GROUP_FK FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (GROUP_ID), 
  PRIMARY KEY (USER_ID, GROUP_ID)
);
CREATE TABLE APPRAISAL (
  APPRAISAL_ID INT IDENTITY PRIMARY KEY, 
  EVALUATED_PERSON_ID INT, 
  APPRAISER_ID INT, 
  EVAL_DATE INT, 
  STATUS INT, 
  CONSTRAINT unique_appraisal_per_year UNIQUE (
    EVALUATED_PERSON_ID, APPRAISER_ID, 
    EVAL_DATE
  )
);
CREATE TABLE APPRAISAL_TYPE (
  APPRAISAL_TYPE_ID INT IDENTITY PRIMARY KEY, 
  APPRAISAL_TYPE_NAME VARCHAR(50)
);

CREATE TABLE SPECIFIC_INTERNAL_APPTYPE (
  GROUP_ID INT, 
  SUBTYPE_ID INT, 
  ROLE_ID INT, 
  WEIGHT INT
);

CREATE TABLE GLOBAL_INTERNAL_APPTYPE (
	GROUP_ID INT, 
	WEIGHT INT
);
	
CREATE TABLE SPECIFIC_APPRAISAL_TYPE (
  APPRAISAL_TYPE_ID INT, 
  SUBTYPE_ID INT, 
  ROLE_ID INT, 
  WEIGHT INT, 
  PRIMARY KEY (
    APPRAISAL_TYPE_ID, SUBTYPE_ID, ROLE_ID
  )
);
CREATE TABLE GLOBAL_APPRAISAL_TYPE (
  APPRAISAL_TYPE_ID INT, 
  ROLE_ID INT, 
  WEIGHT INT, 
  PRIMARY KEY (APPRAISAL_TYPE_ID, ROLE_ID)
);
CREATE TABLE APPRAISAL_ITEM (
  APPRAISAL_ITEM_ID INT IDENTITY PRIMARY KEY, 
  APPRAISAL_TYPE_ID INT, 
  SUBTYPE_ID INT, 
  PARAM_VALUE INT, 
  APPRAISAL_ID INT, 
  CONSTRAINT APPRAISAL_ITEM_FK FOREIGN KEY (APPRAISAL_ID) REFERENCES APPRAISAL (APPRAISAL_ID)
);
CREATE TABLE APPRAISAL_AVERAGES (
  APPRAISAL_ID INT, 
  APPRAISAL_TYPE_ID INT, 
  AVERAGE DECIMAL(4, 2), 
  PRIMARY KEY (APPRAISAL_ID, APPRAISAL_TYPE_ID)
);
CREATE TABLE CRITERIA_NAME (
  CRITERIA_NAME_ID INT IDENTITY PRIMARY KEY, 
  APPRAISAL_TYPE_ID INT, 
  SUBTYPE_ID INT, 
  LANGUAGE INT, 
  CRITERIA_NAME VARCHAR(200)
);
